### PR TITLE
checking if it is completed before setting viewControllers for wPageViewController

### PR DESCRIPTION
**Pull request by nsleche**
this can be the solution for the crash when swiping between tabs a few times issue: #17.

### CODE REVIEW

**Comment by lfarah** [comment]
@marciogranzotto can you check if his fork fixes your bug?

**Comment by marciogranzotto** [comment]
@lfarah nope 😕 same problem

**Comment by lfarah** [comment]
@nschucky did you fix any other bugs here?

**Comment by nsleche** [comment]
no @lfarah, @marciogranzotto make sure your ViewController does not contain another view controller object. For example if your main view controller has a tableview, do not put the UITableViewController with in. you can't have a controller inside another controller.

**Pull request merged**
