### PR TITLE
Added a way to change tab text color.

### PR DESCRIPTION
**Pull request by RigoOnRails**
New property to change the label's color. Extra customizability.

### CODE REVIEW

**Comment by RigoOnRails** [comment]
I'd also for like you to create a `swift-3` branch, so I could submit another pull request, I've updated the code for Swift 3 and I also added my new `tabsTextColor` property.

**Comment by lucoceano** [comment]
@rigobertomolina nice! PR are welcome

**Comment by RigoOnRails** [comment]
Please create a `swift-3` branch!

**Comment by lfarah** [comment]
@rigobertomolina done ✔️ 😄

**Comment by rigobertomolina** [comment]
Oh wow. I was supposed to send ***my*** pull request.

**Comment by rigobertomolina** [comment]
Thanks though!

**Pull request merged**
